import { sequelize } from '../config/database'
import Ingredient from '../models/Ingredient'

const ingredients = [
  'Aether',
  'Albedo',
  "Alchemists' Powder",
  'Alchemy Paste',
  'Alcohest',
  'Alghoul Bone Marrow',
  'Alghoul Claw',
  'Allspice',
  'Amber',
  'Amber Dust',
  'Amber Fragment',
  'Amethyst',
  'Amethyst Dust',
  'Ancient Leshen Mutagen',
  'Arachas Eyes',
  'Arachas Mutagen',
  'Arachas Venom',
  'Archgriffin Mutagen',
  'Arenaria',
  'Balisse Fruit',
  'Basilisk Hide',
  'Basilisk Mutagen',
  'Basilisk Venom',
  'Bear Fat',
  'Beggartick Blossoms',
  'Berbercane Fruit',
  'Berserker Hide',
  'Bison Grass',
  'Black Pearl',
  'Black Pearl Dust',
  'Bloodmoss',
  'Blowball',
  'Blue Mutagen',
  'Bryonia',
  'Buckthorn',
  'Calcium Equum',
  'Cave Troll Liver',
  'Celandine',
  'Cherry Cordial',
  'Chitinous Shell',
  'Chort Hide',
  'Chort Mutagen',
  'Coal',
  'Cockatrice Egg',
  'Cockatrice Mutagen',
  'Cockatrice Stomach',
  'Cortinarius',
  'Cotton',
  "Crow's Eye",
  'Crystalized Essence',
  'Cured Draconid Leather',
  'Cured Leather',
  "Cyclops' Eye",
  'Dark Essence',
  'Dark Iron Ingot',
  'Dark Iron Ore',
  'Dark Iron Plate',
  'Dark Steel Ingot',
  'Dark Steel Plate',
  "Devourer's Blood",
  'Diamond',
  'Diamond Dust',
  'Dimeritium Ingot',
  'Dimeritium Ore',
  'Dimeritium Plate',
  'Dog Tallow',
  'Doppler Mutagen',
  'Dragon Scales',
  'Drowner Brain',
  'Drowner Tongue',
  'Ducal Water',
  "Dwarven Armorer's Tools",
  'Dwarven Spirit',
  'Dwarven Whetstone',
  'Dye',
  'Earth Elemental Mutagen',
  'Ekhidna Mutagen',
  'Ekimmara Hide',
  'Ekimmara Mutagen',
  'Elemental Essence',
  "Elven Armorer's Tools",
  'Elven Whetstone',
  'Emerald',
  'Emerald Dust',
  'Empty Bottle',
  'Endrega Armor Plates',
  'Endrega Embryo',
  'Endrega Heart',
  'Ergot Seeds',
  'Erynia Eye',
  'Essence of Wraith',
  'Feather',
  'Fiber',
  'Fiend Dung',
  'Fiend Mutagen',
  "Fiend's Eye",
  'Fifth Essence',
  'Flawless Amber',
  'Flawless Amethyst',
  'Flawless Diamond',
  'Flawless Emerald',
  'Flawless Ruby',
  'Flawless Sapphire',
  'Foglet Mutagen',
  'Foglet Teeth',
  "Fool's Parsley Leaves",
  'Forktail Hide',
  'Forktail Mutagen',
  'Forktail Spinal Fluid',
  'Fur scrap',
  'Gargoyle Dust',
  'Gargoyle Heart',
  "Ghoul's Blood",
  'Ginatia Petals',
  'Glowing Ore',
  'Glowing Ore Ingot',
  "Gnomish Armorer's Tools",
  'Gnomish Whetstone',
  'Gold Nugget',
  'Gold Ore',
  "Golem's Heart",
  'Grave Hag Mutagen',
  "Grave Hag's Ear",
  'Greater Blue Mutagen',
  'Greater Green Mutagen',
  'Greater Red Mutagen',
  'Green Mold',
  'Green Mutagen',
  'Griffin Feathers',
  'Griffin Mutagen',
  "Griffin's Egg",
  'Han Fiber',
  'Hardened Leather',
  'Hardened Timber',
  'Harpy Eggs',
  'Harpy Feathers',
  'Harpy Talons',
  'Hellebore Petals',
  'Honeysuckle',
  'Hop Umbels',
  'Hornwort',
  'Hydragenum',
  'Infused Crystal',
  'Infused Dust',
  'Infused Shard',
  'Iron Ingot',
  'Iron Ore',
  'Katakan Mutagen',
  'Leather Scraps',
  'Leather Straps',
  'Leshen Mutagen',
  'Leshen Resin',
  'Lesser Blue Mutagen',
  'Lesser Glyph of Infusion',
  'Lesser Green Mutagen',
  'Lesser Red Mutagen',
  'Lesser Runestone',
  'Light Essence',
  'Linen',
  'Lock of Lamia Hair',
  'Longrube',
  'Lunar Shards',
  'Mahakaman Spirit',
  'Mandrake Cordial',
  'Mandrake Root',
  'Manticore Poison Gland',
  'Meteorite Ingot',
  'Meteorite Ore',
  'Meteorite Silver Ingot',
  'Meteorite Silver Plate',
  'Mistletoe',
  'Moleyarrow',
  'Monster Blood',
  'Monster Bone',
  'Monster Brain',
  'Monster Carapace',
  'Monster Claw',
  'Monster Ear',
  'Monster Egg',
  'Monster Essence',
  'Monster Eye',
  'Monster Feather',
  'Monster Hair',
  'Monster Heart',
  'Monster Hide',
  'Monster Liver',
  'Monster Saliva',
  'Monster Tongue',
  'Monster Tooth',
  'Monstrous Fang',
  'Nails',
  'Necrophage Hide',
  'Nekker Blood',
  'Nekker Claw',
  'Nekker Eye',
  'Nekker Heart',
  'Nekker Warrior Mutagen',
  "Nekker Warrior's Liver",
  'Night Wraith Hair',
  'Night Wraith Mutagen',
  'Nigredo',
  'Nilfgaardian Lemon',
  'NoonWraith Mutagen',
  'Nostrix',
  'Oil',
  'Optima Mater',
  'Pearl',
  'Phosphorus',
  'Powdered Monster Tissue',
  'Powdered Pearl',
  'Pringrape',
  'Puffball',
  'Quebrith',
  'Quicksilver Solution',
  'Ranogrin',
  'Rebis',
  'Red Mutagen',
  'Redanian Herbal',
  'Resin',
  'Ribleaf',
  'Rope',
  'Rotfiend Blood',
  'Rubedo',
  'Ruby',
  'Ruby Dust',
  'Saltpeter',
  'Sap',
  'Sapphire',
  'Sapphire Dust',
  'Sewant Mushrooms',
  'Silk',
  'Silver',
  'Silver Ingot',
  'Silver Ore',
  'Silver Plate',
  'Siren Vocal Cords',
  'Specter Dust',
  "Stammelford's Dust",
  'Steel Ingot',
  'Steel Line',
  'Steel Plates',
  'String',
  'Succubus Mutagen',
  'Sulfur',
  'Temerian Rye',
  'Thread',
  'Timber',
  'Troll Hide',
  'Troll Mutagen',
  'Twine',
  'Vampire Fang',
  'Vampire Saliva',
  'Venom Extract',
  'Verbena',
  'Vermilion',
  'Vitriol',
  'Water Essence',
  'Water Hag Mutagen',
  'Water Hag tooth',
  'Wax',
  'Werewolf Hide',
  'Werewolf Mutagen',
  'Werewolf Saliva',
  'White Gull',
  'White Myrtle Petals',
  'Wine Stone',
  'Wire',
  "Wolf's Liver",
  'Wolfsbane',
  'Wraith Mutagen',
  'Wyvern Egg',
  'Wyvern Hide',
  'Wyvern Mutagen',
  'Zerrikanian Powder',
]

async function seedIngredients() {
  try {
    await sequelize.sync()

    for (const name of ingredients) {
      await Ingredient.findOrCreate({ where: { name } }) // avoid duplicates
    }

    console.log('✅ Ingredients seeded successfully')
    process.exit(0)
  } catch (error) {
    console.error('❌ Error seeding ingredients:', error)
    process.exit(1)
  }
}

seedIngredients()

