// @/config/routesConfig.ts


const routesConfig = [
  { path: '/', component: () => import('@/pages/LandingPage/LandingPage') },
  { path: '/home', component: () => import('@/pages/Homepage/Homepage') },
  /*
  { path: '/screen01', component: () => import('@/pages/Screens/Screen01/Screen01') },
  { path: '/screen02', component: () => import('@/pages/Screens/Screen02/Screen02') },
  { path: '/screen03', component: () => import('@/pages/Screens/Screen03/Screen03') },
  { path: '/screen04', component: () => import('@/pages/Screens/Screen04/Screen04') },
  { path: '/screen05', component: () => import('@/pages/Screens/Screen05/Screen05') },
  { path: '/screen06', component: () => import('@/pages/Screens/Screen06/Screen06') },
  { path: '/screen07', component: () => import('@/pages/Screens/Screen07/Screen07') },
  { path: '/screen08', component: () => import('@/pages/Screens/Screen08/Screen08') },
  { path: '/screen09', component: () => import('@/pages/Screens/Screen09/Screen09') },
  { path: '/screen10', component: () => import('@/pages/Screens/Screen10/Screen10') },
  { path: '/screen11', component: () => import('@/pages/Screens/Screen11/Screen11') },
  { path: '/screen12', component: () => import('@/pages/Screens/Screen12/Screen12') },
  { path: '/screen13', component: () => import('@/pages/Screens/Screen13/Screen13') },
  { path: '/screen14', component: () => import('@/pages/Screens/Screen14/Screen14') },
  { path: '/screen15', component: () => import('@/pages/Screens/Screen15/Screen15') },
  { path: '/screen16', component: () => import('@/pages/Screens/Screen16/Screen16') },
  { path: '/screen17', component: () => import('@/pages/Screens/Screen17/Screen17') },
  { path: '/screen18', component: () => import('@/pages/Screens/Screen18/Screen18') },
  { path: '/screen19', component: () => import('@/pages/Screens/Screen19/Screen19') },
  { path: '/screen20', component: () => import('@/pages/Screens/Screen20/Screen20') },
  { path: '/screen21', component: () => import('@/pages/Screens/Screen21/Screen21') },
  { path: '/screen22', component: () => import('@/pages/Screens/Screen22/Screen22') },
  { path: '/screen23', component: () => import('@/pages/Screens/Screen23/Screen23') },
  { path: '/screen24', component: () => import('@/pages/Screens/Screen24/Screen24') },
  { path: '/screen25', component: () => import('@/pages/Screens/Screen25/Screen25') },
  { path: '/screen26', component: () => import('@/pages/Screens/Screen26/Screen26') },
  { path: '/screen27', component: () => import('@/pages/Screens/Screen27/Screen27') },
  { path: '/screen28', component: () => import('@/pages/Screens/Screen28/Screen28') },
  { path: '/screen29', component: () => import('@/pages/Screens/Screen29/Screen29') },
  { path: '/screen30', component: () => import('@/pages/Screens/Screen30/Screen30') },
  { path: '/screen31', component: () => import('@/pages/Screens/Screen31/Screen31') },
  { path: '/screen32', component: () => import('@/pages/Screens/Screen32/Screen32') },
  { path: '/screen33', component: () => import('@/pages/Screens/Screen33/Screen33') },
  { path: '/screen34', component: () => import('@/pages/Screens/Screen34/Screen34') },
  { path: '/screen35', component: () => import('@/pages/Screens/Screen35/Screen35') },
  { path: '/screen36', component: () => import('@/pages/Screens/Screen36/Screen36') },
  { path: '/screen37', component: () => import('@/pages/Screens/Screen37/Screen37') },
  { path: '/screen38', component: () => import('@/pages/Screens/Screen38/Screen38') },
  { path: '/screen39', component: () => import('@/pages/Screens/Screen39/Screen39') },
  { path: '/screen40', component: () => import('@/pages/Screens/Screen40/Screen40') },
  { path: '/screen41', component: () => import('@/pages/Screens/Screen41/Screen41') },
  { path: '/screen42', component: () => import('@/pages/Screens/Screen42/Screen42') },
  { path: '/screen43', component: () => import('@/pages/Screens/Screen43/Screen43') },
  { path: '/screen44', component: () => import('@/pages/Screens/Screen44/Screen44') },
  { path: '/screen45', component: () => import('@/pages/Screens/Screen45/Screen45') },
  { path: '/screen46', component: () => import('@/pages/Screens/Screen46/Screen46') },
  { path: '/screen47', component: () => import('@/pages/Screens/Screen47/Screen47') },
  { path: '/screen48', component: () => import('@/pages/Screens/Screen48/Screen48') },
  { path: '/screen49', component: () => import('@/pages/Screens/Screen49/Screen49') },
  { path: '/screen50', component: () => import('@/pages/Screens/Screen50/Screen50') },
  */
]

export default routesConfig

